name: bloc_event_debouncer
description: >
  A tiny utility package that adds debounce and throttle support to your BLoC event handlers using clean EventTransformers.
version: 0.0.1
homepage: https://github.com/supratim1609/bloc_event_debouncer
repository: https://github.com/supratim1609/bloc_event_debouncer
issue_tracker: https://github.com/supratim1609/bloc_event_debouncer/issues
publish_to: 'https://pub.dev'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  bloc: ^8.1.0
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.0

topics:
  - bloc
  - throttle
  - debounce
  - eventtransformer
  - utilities

